# Generated by Django 5.0.14 on 2025-07-20 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Anmeld',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('anmeld', models.TextField()),
                ('navn', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Fest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('kontakt', models.CharField(max_length=100)),
                ('fest', models.CharField(max_length=100)),
                ('dato', models.DateField()),
                ('tid', models.CharField(max_length=100)),
                ('playlist', models.CharField(max_length=100)),
                ('adresse', models.CharField(max_length=100)),
                ('optrædende', models.CharField(blank=True, max_length=100)),
                ('telt', models.BooleanField(default=True)),
                ('oplysninger', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Mig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('årstal', models.CharField(max_length=100)),
                ('info', models.TextField(blank=True)),
            ],
        ),
    ]
